import type { Metadata } from "next";
import Link from "next/link";
import { requireStaff } from "@/lib/auth-helpers";
import { getWebAnalytics } from "@/lib/web-analytics";
import { LiveSessions } from "./LiveSessions";
import { WebAnalyticsExport } from "./WebAnalyticsExport";

export const metadata: Metadata = { title: "Web análise · Painel" };
export const dynamic = "force-dynamic";
type SearchParams = Promise<{ periodo?: string; de?: string; ate?: string; pagina?: string }>;
function duration(ms: number) { if (!ms) return "—"; const seconds = Math.round(ms / 1000); return seconds < 60 ? `${seconds}s` : `${Math.floor(seconds / 60)}min ${seconds % 60}s`; }
function percent(value: number, total: number) { return total ? Math.round(value / total * 100) : 0; }
function query(filters: Record<string, string | undefined>, page: number) { const params = new URLSearchParams(); Object.entries({ ...filters, pagina: String(page) }).forEach(([key, value]) => value && params.set(key, value)); return `/painel/web-analise?${params}`; }

export default async function WebAnalyticsPage({ searchParams }: { searchParams: SearchParams }) {
  await requireStaff();
  const params = await searchParams;
  const analytics = await getWebAnalytics({ period: params.periodo, from: params.de, to: params.ate, page: Number(params.pagina) || 1 });
  const filters = { periodo: params.periodo, de: params.de, ate: params.ate };
  const maxDaily = Math.max(...analytics.daily.map((item) => item.views), 1);
  const maxPage = Math.max(...analytics.pages.map((item) => item.views), 1);
  return <div className="space-y-5">
    <LiveSessions />
    <WebAnalyticsExport periodo={params.periodo} de={params.de} ate={params.ate} />
    <section className="relative overflow-hidden rounded-[1.75rem] bg-gradient-to-br from-slate-950 via-indigo-950 to-brand p-6 text-white shadow-pop sm:p-8"><div className="absolute -right-16 -top-20 h-72 w-72 rounded-full bg-cyan-400/15 blur-3xl" /><div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-200/70">Inteligência de navegação</p><h1 className="mt-2 font-display text-3xl font-bold">Web análise</h1><p className="mt-2 max-w-2xl text-sm text-white/65">Entenda como visitantes chegam, o que procuram, onde permanecem e quais caminhos levam à compra.</p></div><div className="rounded-2xl border border-white/10 bg-white/10 px-5 py-3 backdrop-blur"><p className="text-[10px] font-bold uppercase tracking-wide text-white/50">Período analisado</p><p className="mt-1 text-sm font-bold">{analytics.range.label}</p></div></div></section>

    <section className="rounded-xl2 border border-line bg-paper p-4 shadow-card"><div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div className="flex flex-wrap gap-2">{[7,30,90,365].map((period) => <Link key={period} href={`/painel/web-analise?periodo=${period}`} className={`rounded-xl border px-4 py-2 text-xs font-bold ${(!params.de && Number(params.periodo ?? 30) === period) ? "border-brand bg-brand text-white" : "border-line hover:border-brand hover:text-brand"}`}>{period === 365 ? "1 ano" : `${period} dias`}</Link>)}</div><form className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><label className="text-[10px] font-bold uppercase tracking-wide text-ink-muted">De<input name="de" type="date" defaultValue={params.de} required className="mt-1 block h-10 rounded-xl border border-line px-3 text-sm text-ink" /></label><label className="text-[10px] font-bold uppercase tracking-wide text-ink-muted">Até<input name="ate" type="date" defaultValue={params.ate} required className="mt-1 block h-10 rounded-xl border border-line px-3 text-sm text-ink" /></label><button className="h-10 self-end rounded-xl bg-slate-900 px-4 text-xs font-bold text-white">Aplicar período</button></form></div></section>

    {analytics.total === 0 ? <section className="grid place-items-center rounded-xl2 border border-dashed border-line bg-paper py-20 text-center"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-brand-soft text-2xl text-brand">◉</span><h2 className="mt-4 font-display text-xl font-bold">A coleta está pronta</h2><p className="mt-2 max-w-md text-sm text-ink-muted">Os dados aparecerão aqui quando visitantes aceitarem cookies analíticos e navegarem pela loja.</p><Link href="/legal/cookies" className="mt-4 text-sm font-bold text-brand hover:underline">Ver política de cookies →</Link></section> : <>
      <section className="grid grid-cols-2 gap-3 xl:grid-cols-5"><Metric label="Visualizações" value={analytics.total.toLocaleString("pt-BR")} note="páginas acessadas" tone="brand" /><Metric label="Visitantes" value={analytics.visitors.toLocaleString("pt-BR")} note="pessoas anônimas" tone="cyan" /><Metric label="Sessões" value={analytics.sessions.toLocaleString("pt-BR")} note={`${(analytics.total / Math.max(1,analytics.sessions)).toFixed(1)} páginas/sessão`} tone="violet" /><Metric label="Permanência média" value={duration(analytics.avgDurationMs)} note="por página concluída" tone="emerald" /><Metric label="Rejeição" value={`${analytics.bounceRate}%`} note="sessões de uma página" tone="amber" /></section>

      <section className="grid gap-5 xl:grid-cols-[minmax(0,1.5fr)_minmax(280px,.7fr)]"><div className="rounded-xl2 border border-line bg-paper p-5 shadow-card"><SectionTitle title="Evolução de acessos" description="Visualizações e visitantes únicos ao longo do período" /><div className="mt-5 flex h-56 items-end gap-1 overflow-hidden border-b border-line">{analytics.daily.map((item, index) => <div key={item.date} className="group relative flex h-full min-w-1 flex-1 items-end"><div className="w-full rounded-t-sm bg-gradient-to-t from-brand to-indigo-400 transition group-hover:from-brand-dark" style={{ height: `${Math.max(2, item.views / maxDaily * 100)}%` }} /><div className="pointer-events-none absolute bottom-full left-1/2 z-10 mb-2 hidden -translate-x-1/2 whitespace-nowrap rounded-lg bg-slate-950 px-2 py-1 text-[10px] text-white group-hover:block">{new Date(`${item.date}T12:00:00`).toLocaleDateString("pt-BR")} · {item.views} acessos · {item.visitors} visitantes</div>{(index === 0 || index === analytics.daily.length - 1) && <span className="absolute -bottom-6 text-[9px] text-ink-muted">{item.date.slice(5).replace("-","/")}</span>}</div>)}</div></div><div className="rounded-xl2 border border-line bg-paper p-5 shadow-card"><SectionTitle title="Dispositivos" description="Como as pessoas acessam" /><Donut rows={analytics.devices} total={analytics.total} /></div></section>

      <section className="grid gap-5 xl:grid-cols-2"><div className="rounded-xl2 border border-line bg-paper p-5 shadow-card"><SectionTitle title="Páginas mais acessadas" description="Volume, alcance e tempo médio" /><div className="mt-4 space-y-3">{analytics.pages.slice(0,8).map((page,index) => <div key={page.path}><div className="flex items-end justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-bold"><span className="mr-2 text-xs text-ink-muted">{index+1}.</span>{page.label}</p><p className="truncate text-[11px] text-ink-muted">{page.path} · {page.visitors} visitantes · {duration(page.avgDurationMs)}</p></div><strong className="text-sm">{page.views}</strong></div><div className="mt-1.5 h-2 overflow-hidden rounded-full bg-mist"><div className="h-full rounded-full bg-brand" style={{width:`${page.views/maxPage*100}%`}} /></div></div>)}</div></div><div className="rounded-xl2 border border-line bg-paper p-5 shadow-card"><SectionTitle title="Produtos mais visualizados" description="Interesse real antes da compra" /><div className="mt-4 divide-y divide-line">{analytics.products.slice(0,8).map((product,index) => <Link key={product.id} href={product.path} target="_blank" className="flex items-center gap-3 py-3 hover:text-brand"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-xl bg-brand-soft text-xs font-black text-brand">{index+1}</span><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{product.name}</strong><small className="text-ink-muted">{product.visitors} visitantes · média {duration(product.avgDurationMs)}</small></span><span className="text-right"><strong className="block">{product.views}</strong><small className="text-ink-muted">views</small></span></Link>)}{!analytics.products.length && <p className="py-8 text-center text-sm text-ink-muted">Ainda não houve visualização de produtos.</p>}</div></div></section>

      <section className="rounded-xl2 border border-line bg-paper p-5 shadow-card"><SectionTitle title="Funil de navegação" description="Da visita até o retorno de compra aprovado" /><div className="mt-5 grid gap-3 sm:grid-cols-4"><FunnelStep label="Sessões" value={analytics.funnel.sessions} total={analytics.funnel.sessions} /><FunnelStep label="Viram produto" value={analytics.funnel.product} total={analytics.funnel.sessions} /><FunnelStep label="Chegaram ao checkout" value={analytics.funnel.checkout} total={analytics.funnel.sessions} /><FunnelStep label="Retornaram em sucesso" value={analytics.funnel.purchase} total={analytics.funnel.sessions} /></div><p className="mt-3 text-[10px] text-ink-muted">O último estágio representa navegação até a página de sucesso; pagamentos confirmados permanecem disponíveis nos Relatórios de vendas.</p></section>

      <section className="grid gap-5 lg:grid-cols-3"><RankCard title="Origens dos acessos" rows={analytics.sources} total={analytics.total} /><RankCard title="Páginas de entrada" rows={analytics.entries} total={analytics.sessions} /><RankCard title="Onde as sessões terminam" rows={analytics.exits} total={analytics.sessions} /></section>

      <section className="grid gap-5 lg:grid-cols-2"><RankCard title="Navegadores" rows={analytics.browsers} total={analytics.total} /><div className="rounded-xl2 border border-line bg-paper p-5 shadow-card"><SectionTitle title="Leitura dos dados" description="Como interpretar os principais sinais" /><ul className="mt-4 space-y-3 text-sm text-ink-soft"><li className="rounded-xl bg-mist p-3"><strong className="text-ink">Muito acesso, pouco tempo:</strong> confira se a página responde rapidamente ao que o visitante procura.</li><li className="rounded-xl bg-mist p-3"><strong className="text-ink">Saída alta em produto:</strong> revise preço, frete, fotos, estoque e clareza do botão de compra.</li><li className="rounded-xl bg-mist p-3"><strong className="text-ink">Checkout abaixo das visualizações:</strong> teste oferta, prova social e comunicação de segurança.</li></ul></div></section>

      <section className="overflow-hidden rounded-xl2 border border-line bg-paper shadow-card"><div className="border-b border-line p-5"><SectionTitle title="Acessos recentes" description="Dados anônimos, com horário de Brasília e paginação" /></div><div className="overflow-x-auto"><table className="min-w-[820px] w-full text-left"><thead className="bg-slate-50 text-[10px] font-bold uppercase tracking-wide text-ink-muted"><tr><th className="px-4 py-3">Data e hora</th><th className="px-4 py-3">Página</th><th className="px-4 py-3">Origem</th><th className="px-4 py-3">Dispositivo</th><th className="px-4 py-3">Navegador</th><th className="px-4 py-3">Permanência</th></tr></thead><tbody className="divide-y divide-line">{analytics.recent.map((visit) => <tr key={visit.id} className="text-sm hover:bg-mist/50"><td className="whitespace-nowrap px-4 py-3 text-xs">{new Date(visit.startedAt).toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo",dateStyle:"short",timeStyle:"short"})}</td><td className="max-w-56 truncate px-4 py-3 font-semibold">{visit.productName || visit.path}</td><td className="max-w-44 truncate px-4 py-3 text-xs text-ink-muted">{visit.utmSource || visit.referrerHost || "Direto"}</td><td className="px-4 py-3 text-xs">{visit.device}</td><td className="px-4 py-3 text-xs">{visit.browser}</td><td className="px-4 py-3 text-xs font-semibold">{duration(visit.durationMs)}</td></tr>)}</tbody></table></div><div className="flex flex-col gap-3 border-t border-line px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-ink-muted">Página {analytics.page} de {analytics.pageCount} · {analytics.total} acesso(s)</p><div className="flex gap-2"><Page href={query(filters,1)} disabled={analytics.page<=1}>«</Page><Page href={query(filters,Math.max(1,analytics.page-1))} disabled={analytics.page<=1}>‹</Page><Page href={query(filters,Math.min(analytics.pageCount,analytics.page+1))} disabled={analytics.page>=analytics.pageCount}>›</Page><Page href={query(filters,analytics.pageCount)} disabled={analytics.page>=analytics.pageCount}>»</Page></div></div></section>
      {analytics.sampled && <p className="rounded-xl bg-amber-50 p-3 text-xs text-amber-800">O período possui mais de 100 mil eventos. Rankings e médias usam uma amostra dos primeiros 100 mil; o total permanece exato.</p>}
    </>}
  </div>;
}

function Metric({label,value,note,tone}:{label:string;value:string;note:string;tone:"brand"|"cyan"|"violet"|"emerald"|"amber"}) { const colors={brand:"from-brand-soft to-white text-brand",cyan:"from-cyan-50 to-white text-cyan-700",violet:"from-violet-50 to-white text-violet-700",emerald:"from-emerald-50 to-white text-emerald-700",amber:"from-amber-50 to-white text-amber-700"}; return <div className={`rounded-xl2 border border-line bg-gradient-to-br p-4 shadow-card ${colors[tone]}`}><p className="text-[10px] font-black uppercase tracking-wide opacity-65">{label}</p><p className="mt-2 font-display text-2xl font-black">{value}</p><p className="mt-1 text-[11px] opacity-65">{note}</p></div>; }
function SectionTitle({title,description}:{title:string;description:string}) { return <div><h2 className="font-display text-lg font-bold">{title}</h2><p className="mt-0.5 text-xs text-ink-muted">{description}</p></div>; }
function Donut({rows,total}:{rows:Array<{name:string;count:number}>;total:number}) { const colors=["bg-brand","bg-cyan-500","bg-violet-500","bg-amber-500"]; return <div className="mt-5 space-y-3">{rows.map((row,index)=><div key={row.name}><div className="flex justify-between text-xs"><span className="font-semibold">{row.name}</span><span>{row.count} · {percent(row.count,total)}%</span></div><div className="mt-1 h-2 rounded-full bg-mist"><div className={`h-full rounded-full ${colors[index%colors.length]}`} style={{width:`${percent(row.count,total)}%`}} /></div></div>)}</div>; }
function FunnelStep({label,value,total}:{label:string;value:number;total:number}) { return <div className="relative overflow-hidden rounded-xl border border-line bg-mist/50 p-4"><p className="text-xs font-bold text-ink-muted">{label}</p><p className="mt-2 font-display text-2xl font-black">{value}</p><p className="text-xs font-semibold text-brand">{percent(value,total)}% das sessões</p><div className="absolute bottom-0 left-0 h-1 bg-brand" style={{width:`${percent(value,total)}%`}} /></div>; }
function RankCard({title,rows,total}:{title:string;rows:Array<{name:string;count:number}>;total:number}) { return <div className="rounded-xl2 border border-line bg-paper p-5 shadow-card"><SectionTitle title={title} description="Participação no período selecionado" /><div className="mt-4 space-y-3">{rows.slice(0,6).map((row,index)=><div key={row.name} className="flex items-center gap-3"><span className="grid h-7 w-7 place-items-center rounded-lg bg-mist text-[10px] font-black">{index+1}</span><span className="min-w-0 flex-1 truncate text-xs font-semibold">{row.name}</span><span className="text-xs text-ink-muted">{row.count} · {percent(row.count,total)}%</span></div>)}{!rows.length&&<p className="text-sm text-ink-muted">Sem dados neste período.</p>}</div></div>; }
function Page({href,disabled,children}:{href:string;disabled:boolean;children:React.ReactNode}) { return <Link href={href} className={`grid h-9 w-9 place-items-center rounded-lg border border-line ${disabled?"pointer-events-none opacity-35":"hover:border-brand hover:text-brand"}`}>{children}</Link>; }
