"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
type Row = Record<string, string | number>;
const reports = [{ id: "sales", icon: "↗", title: "Vendas", text: "Faturamento e pedidos por dia" }, { id: "orders", icon: "□", title: "Pedidos", text: "Operação completa de cada compra" }, { id: "products", icon: "▦", title: "Produtos", text: "Catálogo, preços e estoque" }, { id: "customers", icon: "♙", title: "Clientes", text: "Aquisição e relacionamento" }, { id: "payments", icon: "$", title: "Pagamentos", text: "Distribuição por modalidade" }, { id: "service", icon: "★", title: "Atendimento", text: "Dúvidas, notas e reembolsos" }];
const formats = [{ value: "pdf", label: "PDF" }, { value: "xlsx", label: "XLSX" }, { value: "xls", label: "XLS" }, { value: "csv", label: "CSV" }, { value: "json", label: "JSON" }, { value: "svg", label: "SVG" }];
const PAGE_SIZE = 10;
export function ReportExplorerV2({ rows, period, from, to, initialType = "orders" }: { rows: Record<string, Row[]>; period: string; from?: string; to?: string; initialType?: string }) {
  const [type, setType] = useState(initialType); const [view, setView] = useState<"table" | "visual">("table"); const [page, setPage] = useState(1); const [q, setQ] = useState(""); const [status, setStatus] = useState("all"); const [category, setCategory] = useState("all"); const [stock, setStock] = useState("all"); const [active, setActive] = useState("all"); const [minValue, setMinValue] = useState("");
  const source = rows[type] ?? []; const selected = reports.find((report) => report.id === type)!;
  const options = (field: string) => [...new Set(source.map((row) => String(row[field] ?? "")).filter(Boolean))].sort();
  const filtered = useMemo(() => source.filter((row) => { const haystack = Object.values(row).join(" ").toLocaleLowerCase("pt-BR"); if (q && !haystack.includes(q.toLocaleLowerCase("pt-BR"))) return false; if (status !== "all" && String(row.Status) !== status) return false; if (category !== "all" && String(row.Categoria) !== category) return false; if (active !== "all" && String(row.Situação) !== active) return false; if (stock === "zero" && Number(row.Estoque) !== 0) return false; if (stock === "critical" && (Number(row.Estoque) <= 0 || Number(row.Estoque) > 5)) return false; if (stock === "healthy" && Number(row.Estoque) <= 5) return false; const cents = Number(row["Total (centavos)"] ?? row["Faturamento (centavos)"] ?? 0); if (minValue && cents < Number(minValue) * 100) return false; return true; }), [source, q, status, category, active, stock, minValue]);
  useEffect(() => setPage(1), [type, q, status, category, active, stock, minValue]);
  const pages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const current = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE); const headers = Object.keys(source[0] ?? {}); const filterQuery = new URLSearchParams({ period, type, ...(from ? { from } : {}), ...(to ? { to } : {}), ...(q ? { q } : {}), ...(status !== "all" ? { status } : {}), ...(category !== "all" ? { category } : {}), ...(stock !== "all" ? { stock } : {}), ...(active !== "all" ? { active } : {}), ...(minValue ? { minValue } : {}) }).toString();
  function changeType(next: string) { setType(next); setQ(""); setStatus("all"); setCategory("all"); setStock("all"); setActive("all"); setMinValue(""); setView(next === "sales" || next === "payments" ? "visual" : "table"); }
  return <section className="overflow-hidden rounded-[1.5rem] border border-line bg-paper shadow-pop"><div className="bg-gradient-to-r from-slate-950 via-brand-dark to-brand p-6 text-white"><p className="text-xs font-bold uppercase tracking-[0.18em] text-white/55">Explorador de dados</p><h3 className="mt-1 font-display text-2xl font-semibold">Visualize, filtre e investigue</h3><p className="mt-2 text-sm text-white/65">Cada relatório possui filtros e uma visualização própria. Exporte somente quando estiver pronto.</p></div><div className="p-5 sm:p-6">
    <form className="grid gap-3 rounded-xl2 border border-line bg-mist p-4 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><label className="label-filter">Data inicial<input type="date" name="from" defaultValue={from} max={to} className="input-filter" /></label><label className="label-filter">Data final<input type="date" name="to" defaultValue={to} min={from} className="input-filter" /></label><input type="hidden" name="type" value={type} /><button className="h-11 rounded-xl bg-brand px-5 text-sm font-bold text-white hover:bg-brand-dark">Aplicar período</button></form>
    <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{reports.map((report) => <button key={report.id} type="button" onClick={() => changeType(report.id)} className={`flex items-center gap-3 rounded-xl2 border p-4 text-left transition hover:-translate-y-0.5 ${type === report.id ? "border-brand bg-brand-soft shadow-card" : "border-line hover:border-brand/40"}`}><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl font-display text-lg font-bold ${type === report.id ? "bg-brand text-white" : "bg-mist text-brand"}`}>{report.icon}</span><span><span className="block text-sm font-bold">{report.title}</span><span className="mt-0.5 block text-xs text-ink-muted">{report.text}</span></span></button>)}</div>
    <div className="mt-5 rounded-xl2 border border-line bg-mist/60 p-4"><div className="flex flex-wrap gap-3"><label className="min-w-48 flex-1 text-xs font-semibold text-ink-muted">BUSCAR<input value={q} onChange={(event) => setQ(event.target.value)} placeholder={type === "orders" ? "Pedido, cliente, produto..." : "Buscar neste relatório..."} className="input-filter" /></label>{type === "orders" && <><Select label="STATUS" value={status} onChange={setStatus} options={options("Status")} /><label className="w-40 text-xs font-semibold text-ink-muted">VALOR MÍNIMO<input type="number" min="0" value={minValue} onChange={(event) => setMinValue(event.target.value)} placeholder="R$ 0,00" className="input-filter" /></label></>}{type === "products" && <><Select label="CATEGORIA" value={category} onChange={setCategory} options={options("Categoria")} /><Select label="SITUAÇÃO" value={active} onChange={setActive} options={options("Situação")} /><label className="w-44 text-xs font-semibold text-ink-muted">ESTOQUE<select value={stock} onChange={(event) => setStock(event.target.value)} className="input-filter"><option value="all">Todos</option><option value="zero">Sem estoque</option><option value="critical">Crítico (1–5)</option><option value="healthy">Saudável (+5)</option></select></label></>}{type === "sales" && <label className="w-44 text-xs font-semibold text-ink-muted">FATURAMENTO MÍNIMO<input type="number" min="0" value={minValue} onChange={(event) => setMinValue(event.target.value)} className="input-filter" /></label>}</div></div>
    <div className="mt-5 flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="font-display text-xl font-semibold">{selected.title}</p><p className="text-sm text-ink-muted">{filtered.length} de {source.length} registro(s) após os filtros</p></div><div className="flex flex-wrap gap-2"><div className="mr-2 flex rounded-lg border border-line p-1"><button onClick={() => setView("table")} className={`rounded-md px-3 py-1.5 text-xs font-bold ${view === "table" ? "bg-brand text-white" : "hover:bg-mist"}`}>Tabela</button><button onClick={() => setView("visual")} className={`rounded-md px-3 py-1.5 text-xs font-bold ${view === "visual" ? "bg-brand text-white" : "hover:bg-mist"}`}>Visual</button></div>{formats.map((format) => <a key={format.value} href={`/api/painel/relatorios?${filterQuery}&format=${format.value}`} className="rounded-lg border border-line px-3 py-2 text-xs font-bold hover:border-brand hover:bg-brand-soft">↓ {format.label}</a>)}</div></div>
    <div className="mt-4 flex h-[520px] flex-col overflow-hidden rounded-xl border border-line bg-white">{view === "table" ? <Table rows={current} headers={headers} type={type} /> : <Visual rows={current} type={type} />}<Pagination page={page} pages={pages} total={filtered.length} onPage={setPage} /></div>
  </div></section>;
}
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[] }) { return <label className="w-48 text-xs font-semibold text-ink-muted">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="input-filter"><option value="all">Todos</option>{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
function Table({ rows, headers, type }: { rows: Row[]; headers: string[]; type: string }) { return <div className="flex-1 overflow-auto"><table className="min-w-full whitespace-nowrap text-left"><thead className="sticky top-0 z-10 bg-slate-900 text-white"><tr>{headers.map((header) => <th key={header} className="px-4 py-3 text-xs uppercase tracking-wide">{header}</th>)}</tr></thead><tbody className="divide-y divide-line">{rows.map((row, index) => <tr key={index} className="even:bg-mist/60 hover:bg-brand-soft/40">{headers.map((header) => <td key={header} className="max-w-72 truncate px-4 py-3 text-sm">{type === "orders" && header === "Pedido" ? <Link href={`/painel/pedidos/${row[header]}`} className="font-mono font-bold text-brand hover:underline">#{String(row[header]).slice(-8)} ↗</Link> : formatCell(header, row[header])}</td>)}</tr>)}</tbody></table>{!rows.length && <Empty />}</div>; }
function Visual({ rows, type }: { rows: Row[]; type: string }) { const max = Math.max(...rows.map((row) => Number(row["Faturamento (centavos)"] ?? row.Pedidos ?? row.Estoque ?? 0)), 1); return <div className="grid flex-1 auto-rows-min gap-3 overflow-auto bg-mist/50 p-4 sm:grid-cols-2">{rows.map((row, index) => type === "orders" ? <Link key={index} href={`/painel/pedidos/${row.Pedido}`} className="rounded-xl border border-line bg-white p-4 shadow-card hover:border-brand"><div className="flex justify-between"><strong className="font-mono text-brand">#{String(row.Pedido).slice(-8)}</strong><span className="rounded-full bg-brand-soft px-2 py-1 text-[10px] font-bold text-brand">{row.Status}</span></div><p className="mt-3 truncate text-sm font-semibold">{row.Cliente}</p><p className="mt-1 line-clamp-2 text-xs text-ink-muted">{row.Produtos}</p><p className="mt-3 font-display text-xl font-bold">{formatCell("centavos", row["Total (centavos)"])}</p></Link> : <div key={index} className="rounded-xl border border-line bg-white p-4 shadow-card"><p className="truncate text-sm font-bold">{String(row.Produto ?? row.Data ?? row["Meio de pagamento"] ?? row.Cliente ?? Object.values(row)[0])}</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-mist"><div className="h-full rounded-full bg-brand" style={{ width: `${Math.max(4, Number(row["Faturamento (centavos)"] ?? row.Pedidos ?? row.Estoque ?? 0) / max * 100)}%` }} /></div><div className="mt-3 space-y-1 text-xs text-ink-muted">{Object.entries(row).slice(1, 5).map(([key, value]) => <p key={key}><span>{key}:</span> <strong className="text-ink">{formatCell(key, value)}</strong></p>)}</div></div>)}{!rows.length && <Empty />}</div>; }
function Pagination({ page, pages, total, onPage }: { page: number; pages: number; total: number; onPage: (page: number) => void }) { return <div className="flex items-center justify-between border-t border-line bg-white px-4 py-3"><p className="text-xs text-ink-muted">{total ? `${(page - 1) * PAGE_SIZE + 1}–${Math.min(page * PAGE_SIZE, total)} de ${total}` : "0 registros"}</p><div className="flex items-center gap-1"><PageButton label="«" disabled={page === 1} action={() => onPage(1)} /><PageButton label="‹" disabled={page === 1} action={() => onPage(page - 1)} /><span className="min-w-24 text-center text-xs font-semibold">Página {page} de {pages}</span><PageButton label="›" disabled={page === pages} action={() => onPage(page + 1)} /><PageButton label="»" disabled={page === pages} action={() => onPage(pages)} /></div></div>; }
function PageButton({ label, disabled, action }: { label: string; disabled: boolean; action: () => void }) { return <button type="button" disabled={disabled} onClick={action} className="grid h-8 w-8 place-items-center rounded-lg border border-line font-bold hover:bg-brand-soft disabled:opacity-30">{label}</button>; }
function formatCell(header: string, value: string | number) { if (typeof value === "number" && header.toLowerCase().includes("centavos")) return (value / 100).toLocaleString("pt-BR", { style: "currency", currency: "BRL" }); return String(value ?? "—"); }
function Empty() { return <div className="col-span-full m-auto p-12 text-center text-sm text-ink-muted">Nenhum registro corresponde aos filtros.</div>; }
