"use client";
import { useState } from "react";
type Row = Record<string, string | number>;
const reports = [{ id: "sales", icon: "↗", title: "Vendas", text: "Faturamento e pedidos por dia" }, { id: "orders", icon: "□", title: "Pedidos", text: "Detalhes, status, cliente e total" }, { id: "products", icon: "▦", title: "Produtos", text: "Catálogo, preços e estoque" }, { id: "customers", icon: "♙", title: "Clientes", text: "Aquisição e compradores" }, { id: "payments", icon: "$", title: "Pagamentos", text: "Distribuição por modalidade" }, { id: "service", icon: "★", title: "Atendimento", text: "Dúvidas, notas e reembolsos" }];
const formats = [{ value: "pdf", label: "PDF" }, { value: "xlsx", label: "Excel XLSX" }, { value: "xls", label: "Excel XLS" }, { value: "csv", label: "CSV" }, { value: "json", label: "JSON" }, { value: "svg", label: "Imagem SVG" }];
export function ReportExplorer({ rows, totals, period, from, to, initialType = "sales" }: { rows: Record<string, Row[]>; totals: Record<string, number>; period: string; from?: string; to?: string; initialType?: string }) {
  const [type, setType] = useState(initialType); const selected = reports.find((report) => report.id === type)!; const data = rows[type] ?? []; const headers = Object.keys(data[0] ?? {}); const query = new URLSearchParams({ period, type, ...(from ? { from } : {}), ...(to ? { to } : {}) }).toString();
  return <section className="overflow-hidden rounded-[1.5rem] border border-line bg-paper shadow-pop"><div className="border-b border-line bg-gradient-to-r from-slate-950 via-brand-dark to-brand p-6 text-white"><p className="text-xs font-bold uppercase tracking-[0.18em] text-white/55">Explorador de dados</p><h3 className="mt-1 font-display text-2xl font-semibold">Visualize antes de exportar</h3><p className="mt-2 text-sm text-white/65">Escolha o relatório, defina as datas e confira cada informação na planilha abaixo.</p></div><div className="p-5 sm:p-6">
    <form className="grid gap-3 rounded-xl2 border border-line bg-mist p-4 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><label className="text-xs font-bold uppercase tracking-wide text-ink-muted">Data inicial<input type="date" name="from" defaultValue={from} max={to} className="mt-1 h-11 w-full rounded-xl border border-line bg-white px-3 text-sm text-ink" /></label><label className="text-xs font-bold uppercase tracking-wide text-ink-muted">Data final<input type="date" name="to" defaultValue={to} min={from} className="mt-1 h-11 w-full rounded-xl border border-line bg-white px-3 text-sm text-ink" /></label><input type="hidden" name="type" value={type} /><button className="h-11 rounded-xl bg-brand px-5 text-sm font-bold text-white hover:bg-brand-dark">Aplicar período</button></form>
    <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{reports.map((report) => <button key={report.id} type="button" onClick={() => setType(report.id)} className={`flex items-center gap-3 rounded-xl2 border p-4 text-left transition hover:-translate-y-0.5 ${type === report.id ? "border-brand bg-brand-soft shadow-card" : "border-line hover:border-brand/40"}`}><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl font-display text-lg font-bold ${type === report.id ? "bg-brand text-white" : "bg-mist text-brand"}`}>{report.icon}</span><span><span className="block text-sm font-bold">{report.title}</span><span className="mt-0.5 block text-xs text-ink-muted">{report.text}</span></span></button>)}</div>
    <div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-display text-xl font-semibold">Planilha de {selected.title}</p><p className="text-sm text-ink-muted">{totals[type] ?? 0} registro(s) no período · mostrando até 100 na prévia</p></div><div className="flex flex-wrap gap-2">{formats.map((format) => <a key={format.value} href={`/api/painel/relatorios?${query}&format=${format.value}`} className="rounded-lg border border-line bg-white px-3 py-2 text-xs font-bold hover:border-brand hover:bg-brand-soft hover:text-brand">↓ {format.label}</a>)}</div></div>
    <div className="mt-4 overflow-auto rounded-xl border border-line"><table className="min-w-full whitespace-nowrap text-left text-sm"><thead className="sticky top-0 bg-slate-900 text-white"><tr>{headers.map((header) => <th key={header} className="px-4 py-3 text-xs font-semibold uppercase tracking-wide">{header}</th>)}</tr></thead><tbody className="divide-y divide-line">{data.map((row, index) => <tr key={index} className="odd:bg-white even:bg-mist/60 hover:bg-brand-soft/40">{headers.map((header) => <td key={header} className="max-w-xs truncate px-4 py-3">{formatCell(header, row[header])}</td>)}</tr>)}</tbody></table>{!data.length && <div className="p-10 text-center text-sm text-ink-muted">Nenhum dado encontrado para este relatório e período.</div>}</div>
  </div></section>;
}
function formatCell(header: string, value: string | number) { if (typeof value === "number" && header.toLowerCase().includes("centavos")) return (value / 100).toLocaleString("pt-BR", { style: "currency", currency: "BRL" }); return String(value ?? "—"); }
