"use client";

import { useState } from "react";
import { toPng } from "html-to-image";

export function ReportOverviewActions() {
  const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string>();
  async function sections() { const root = document.getElementById("report-overview-export"); if (!root) throw new Error("Visão do relatório não encontrada."); const nodes = [...root.querySelectorAll<HTMLElement>("[data-export-section]")]; return Promise.all(nodes.map((node) => toPng(node, { backgroundColor: "#f7f8fc", pixelRatio: 1.5, cacheBust: true })) ); }
  async function exportImage() { setBusy("imagem"); setError(undefined); try { const root = document.getElementById("report-overview-export"); if (!root) throw new Error("Relatório não encontrado."); download(await toPng(root, { backgroundColor: "#f7f8fc", pixelRatio: 1.5, cacheBust: true }), `voltaria-visao-geral-${date()}.png`); } catch (e) { setError(message(e)); } finally { setBusy(null); } }
  async function exportPdf() { setBusy("pdf"); setError(undefined); try { const [{ PDFDocument }, images] = await Promise.all([import("pdf-lib"), sections()]); const pdf = await PDFDocument.create(); for (const data of images) { const bytes = await fetch(data).then((response) => response.arrayBuffer()); const image = await pdf.embedPng(bytes); const pageWidth = 842; const pageHeight = Math.max(595, pageWidth * image.height / image.width); const page = pdf.addPage([pageWidth, pageHeight]); page.drawImage(image, { x: 0, y: 0, width: pageWidth, height: pageHeight }); } const blob = new Blob([await pdf.save() as BlobPart], { type: "application/pdf" }); download(URL.createObjectURL(blob), `voltaria-visao-geral-${date()}.pdf`, true); } catch (e) { setError(message(e)); } finally { setBusy(null); } }
  async function exportSlides() { setBusy("slides"); setError(undefined); try { const images = await sections(); const html = `<!doctype html><html xmlns:p="urn:schemas-microsoft-com:office:powerpoint"><head><meta charset="utf-8"><title>Relatório Voltaria</title><style>@page{size:13.333in 7.5in;margin:0}body{margin:0;background:#f7f8fc}section{width:13.333in;height:7.5in;display:flex;align-items:center;justify-content:center;page-break-after:always}img{max-width:100%;max-height:100%;object-fit:contain}</style></head><body>${images.map((data) => `<section><img src="${data}"></section>`).join("")}</body></html>`; const blob = new Blob([html], { type: "application/vnd.ms-powerpoint" }); download(URL.createObjectURL(blob), `voltaria-visao-geral-${date()}.ppt`, true); } catch (e) { setError(message(e)); } finally { setBusy(null); } }
  return <div className="flex flex-col items-start gap-2 sm:items-end"><p className="text-xs font-semibold uppercase tracking-wide text-ink-muted">Exportar visão completa</p><div className="flex flex-wrap gap-2"><Action label="Imagem PNG" active={busy === "imagem"} action={exportImage} /><Action label="Documento PDF" active={busy === "pdf"} action={exportPdf} /><Action label="Slides PPT" active={busy === "slides"} action={exportSlides} /></div>{error && <p className="max-w-md text-xs text-red-600">{error}</p>}</div>;
}
function Action({ label, active, action }: { label: string; active: boolean; action: () => void }) { return <button type="button" disabled={active} onClick={action} className="rounded-xl border border-line bg-paper px-3 py-2 text-xs font-bold shadow-card hover:border-brand hover:bg-brand-soft disabled:opacity-60">{active ? "Gerando..." : `↓ ${label}`}</button>; }
function date() { return new Date().toISOString().slice(0, 10); }
function message(error: unknown) { return error instanceof Error ? error.message : "Não foi possível gerar o arquivo."; }
function download(url: string, filename: string, revoke = false) { const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); if (revoke) window.setTimeout(() => URL.revokeObjectURL(url), 1000); }
