import { NextResponse } from "next/server";
import { requireStaff } from "@/lib/auth-helpers";
import { getReports, reportRows, REPORT_PERIODS, type ReportPeriod, type ReportType } from "@/lib/reports";

const types = ["sales", "orders", "products", "customers", "payments", "service"] as const;
const formats = ["pdf", "xlsx", "xls", "csv", "json", "svg"] as const;
const names: Record<ReportType, string> = { sales: "vendas", orders: "pedidos", products: "produtos-estoque", customers: "clientes", payments: "pagamentos", service: "atendimento" };
const esc = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!);

export async function GET(request: Request) {
  await requireStaff();
  const params = new URL(request.url).searchParams;
  const period = REPORT_PERIODS.includes(params.get("period") as ReportPeriod) ? params.get("period") as ReportPeriod : "30";
  const type = types.includes(params.get("type") as ReportType) ? params.get("type") as ReportType : "sales";
  const format = formats.includes(params.get("format") as typeof formats[number]) ? params.get("format") as typeof formats[number] : "csv";
  const from = parseDate(params.get("from"), false); const to = parseDate(params.get("to"), true); const custom = from && to && from <= to ? { from, to } : undefined;
  const data = await getReports(period, custom); const rows = applyFilters(reportRows(data, type), params); const headers = Object.keys(rows[0] ?? { Informação: "Sem dados" }); const normalized = rows.length ? rows : [{ Informação: "Sem dados no período" }];
  const filename = `heca-store-${names[type]}-${new Date().toISOString().slice(0, 10)}`;
  if (format === "json") return download(JSON.stringify({ report: type, period, generatedAt: data.generatedAt, rows: normalized }, null, 2), "application/json; charset=utf-8", `${filename}.json`);
  if (format === "csv") { const csv = [headers, ...normalized.map((row) => headers.map((header) => row[header] ?? ""))].map((line) => line.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(";")).join("\r\n"); return download(`\uFEFF${csv}`, "text/csv; charset=utf-8", `${filename}.csv`); }
  if (format === "xls") { const html = `<!doctype html><html><meta charset="utf-8"><table><thead><tr>${headers.map((header) => `<th>${esc(header)}</th>`).join("")}</tr></thead><tbody>${normalized.map((row) => `<tr>${headers.map((header) => `<td>${esc(row[header])}</td>`).join("")}</tr>`).join("")}</tbody></table></html>`; return download(html, "application/vnd.ms-excel; charset=utf-8", `${filename}.xls`); }
  if (format === "xlsx") { const writeXlsxFile = (await import("write-excel-file/node")).default; const sheet = [headers.map((header) => ({ value: header, fontWeight: "bold" as const, backgroundColor: "#A100FF", color: "#FFFFFF" })), ...normalized.map((row) => headers.map((header) => ({ value: String(row[header] ?? ""), wrap: true })))]; const file = await writeXlsxFile(sheet, { columns: headers.map((header) => ({ width: Math.min(45, Math.max(14, header.length + 4)) })) }); const buffer = await file.toBuffer(); return new NextResponse(new Uint8Array(buffer), { headers: fileHeaders("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", `${filename}.xlsx`) }); }
  if (format === "svg") { const width = 1200; const lineHeight = 34; const shown = normalized.slice(0, 24); const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${180 + shown.length * lineHeight}" viewBox="0 0 ${width} ${180 + shown.length * lineHeight}"><rect width="100%" height="100%" fill="#f7f8fc"/><rect width="100%" height="110" fill="#21002F"/><text x="50" y="52" fill="white" font-family="Arial" font-size="28" font-weight="700">Relatório Heca Store · ${esc(names[type])}</text><text x="50" y="82" fill="#E8C3FF" font-family="Arial" font-size="14">Gerado em ${new Date().toLocaleString("pt-BR", { timeZone: "America/Sao_Paulo" })}</text>${shown.map((row, index) => `<rect x="35" y="${130 + index * lineHeight}" width="1130" height="28" rx="7" fill="${index % 2 ? "#ffffff" : "#F5E8FF"}"/><text x="50" y="${150 + index * lineHeight}" fill="#1d2433" font-family="Arial" font-size="12">${esc(headers.map((header) => `${header}: ${row[header] ?? ""}`).join("   ·   ")).slice(0, 190)}</text>`).join("")}</svg>`; return download(svg, "image/svg+xml; charset=utf-8", `${filename}.svg`); }
  const { PDFDocument, StandardFonts, rgb } = await import("pdf-lib"); const pdf = await PDFDocument.create(); const font = await pdf.embedFont(StandardFonts.Helvetica); const bold = await pdf.embedFont(StandardFonts.HelveticaBold); let page = pdf.addPage([842, 595]); let y = 540; const addHeader = () => { page.drawRectangle({ x: 0, y: 530, width: 842, height: 65, color: rgb(0.18, 0, 0.28) }); page.drawText(`Relatorio Heca Store - ${names[type]}`, { x: 35, y: 558, size: 20, font: bold, color: rgb(1, 1, 1) }); y = 505; }; addHeader(); for (const row of normalized) { if (y < 40) { page = pdf.addPage([842, 595]); addHeader(); } const line = headers.map((header) => `${header}: ${row[header] ?? ""}`).join(" | ").replace(/[^\x20-\x7EÀ-ÿ]/g, " ").slice(0, 145); page.drawText(line, { x: 35, y, size: 8.5, font, color: rgb(0.12, 0.15, 0.22) }); y -= 18; } const bytes = await pdf.save(); return new NextResponse(bytes as BodyInit, { headers: fileHeaders("application/pdf", `${filename}.pdf`) });
}

function fileHeaders(contentType: string, filename: string) { return { "Content-Type": contentType, "Content-Disposition": `attachment; filename="${filename}"`, "Cache-Control": "no-store" }; }
function download(body: string, contentType: string, filename: string) { return new NextResponse(body, { headers: fileHeaders(contentType, filename) }); }
function parseDate(value: string | null, end: boolean) { if (!value || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return undefined; const date = new Date(`${value}T${end ? "23:59:59.999" : "00:00:00"}-03:00`); return Number.isNaN(date.getTime()) ? undefined : date; }
function applyFilters(rows: Array<Record<string, string | number>>, params: URLSearchParams) { const q = params.get("q")?.toLocaleLowerCase("pt-BR"); const status = params.get("status"); const category = params.get("category"); const stock = params.get("stock"); const active = params.get("active"); const minValue = Number(params.get("minValue") ?? 0) * 100; return rows.filter((row) => { if (q && !Object.values(row).join(" ").toLocaleLowerCase("pt-BR").includes(q)) return false; if (status && String(row.Status) !== status) return false; if (category && String(row.Categoria) !== category) return false; if (active && String(row.Situação) !== active) return false; if (stock === "zero" && Number(row.Estoque) !== 0) return false; if (stock === "critical" && (Number(row.Estoque) <= 0 || Number(row.Estoque) > 5)) return false; if (stock === "healthy" && Number(row.Estoque) <= 5) return false; const cents = Number(row["Total (centavos)"] ?? row["Faturamento (centavos)"] ?? 0); return !minValue || cents >= minValue; }); }
