import Link from "next/link";
import { getAdminProducts } from "@/lib/admin";
import { formatBRL } from "@/lib/format";

export type ProductFilters = { q?: string; category?: string; visibility?: string; stock?: string; sort?: string; page?: string };

function url(current: ProductFilters, changes: Record<string, string | number | undefined>) {
  const params = new URLSearchParams();
  Object.entries({ ...current, ...changes }).forEach(([key, value]) => { if (value !== undefined && value !== "" && value !== "all") params.set(key, String(value)); });
  return `/painel/produtos?${params}`;
}

export async function ProductCatalogDashboard({ filters }: { filters: ProductFilters }) {
  const data = await getAdminProducts({ q: filters.q, category: filters.category, visibility: filters.visibility as never, stock: filters.stock as never, sort: filters.sort as never, page: Math.max(Number(filters.page) || 1, 1), pageSize: 10 });
  const page = Math.min(data.page, data.pageCount);
  const from = data.total ? (page - 1) * data.pageSize + 1 : 0;
  const to = Math.min(page * data.pageSize, data.total);
  const filtered = filters.q || filters.category || (filters.visibility && filters.visibility !== "all") || (filters.stock && filters.stock !== "all");

  return <div className="space-y-5">
    <section className="relative overflow-hidden rounded-[1.75rem] bg-gradient-to-br from-slate-950 via-slate-900 to-brand-dark p-6 text-white shadow-pop sm:p-7"><div className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-brand/30 blur-3xl" /><div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-white/50">Gestão do catálogo</p><h1 className="mt-2 font-display text-3xl font-bold">Produtos e estoque</h1><p className="mt-2 max-w-xl text-sm text-white/65">Organize o catálogo, identifique rupturas de estoque e mantenha as ofertas da loja sempre atualizadas.</p></div><Link href="/painel/produtos/novo" className="inline-flex h-12 items-center justify-center rounded-xl bg-white px-5 text-sm font-black text-slate-950 shadow-card transition hover:-translate-y-0.5 hover:bg-brand-soft">＋ Cadastrar produto</Link></div></section>

    <section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Ativos na loja" value={data.stats.active} color="emerald" note="visíveis para clientes" /><Metric label="Estoque crítico" value={data.stats.lowStock} color="amber" note="até 5 unidades" /><Metric label="Em destaque" value={data.stats.featured} color="brand" note="promovidos na vitrine" /><Metric label="Inativos" value={data.stats.inactive} color="slate" note="ocultos da loja" /></section>

    <section className="rounded-xl2 border border-line bg-paper p-4 shadow-card sm:p-5"><form className="grid gap-3 lg:grid-cols-[minmax(220px,1.4fr)_repeat(3,minmax(150px,1fr))_auto]"><input name="q" defaultValue={filters.q} placeholder="Produto, marca ou SKU..." className="h-11 rounded-xl border border-line bg-mist px-4 text-sm outline-none focus:border-brand focus:bg-white focus:ring-2 focus:ring-brand/10" /><select name="category" defaultValue={filters.category ?? ""} className="h-11 rounded-xl border border-line bg-white px-3 text-sm"><option value="">Todas as categorias</option>{data.categories.map((category) => <option key={category.id} value={category.id}>{category.name} ({category._count.products})</option>)}</select><select name="visibility" defaultValue={filters.visibility ?? "all"} className="h-11 rounded-xl border border-line bg-white px-3 text-sm"><option value="all">Qualquer visibilidade</option><option value="active">Ativos</option><option value="inactive">Inativos</option><option value="featured">Em destaque</option></select><select name="stock" defaultValue={filters.stock ?? "all"} className="h-11 rounded-xl border border-line bg-white px-3 text-sm"><option value="all">Qualquer estoque</option><option value="out">Sem estoque</option><option value="low">Estoque baixo</option><option value="available">Estoque disponível</option></select><button className="h-11 rounded-xl bg-brand px-5 text-sm font-bold text-white hover:bg-brand-dark">Filtrar</button><div className="flex flex-wrap items-center gap-2 lg:col-span-5"><span className="text-xs font-bold uppercase tracking-wide text-ink-muted">Ordenar:</span>{[["newest","Recentes"],["name","Nome A–Z"],["price_high","Maior preço"],["price_low","Menor preço"],["stock","Menor estoque"]].map(([value,label]) => <Link key={value} href={url(filters,{sort:value,page:1})} className={`rounded-lg px-3 py-1.5 text-xs font-semibold ${(filters.sort ?? "newest") === value ? "bg-slate-900 text-white" : "bg-mist text-ink-soft hover:bg-line"}`}>{label}</Link>)}{filtered && <Link href="/painel/produtos" className="ml-auto text-xs font-semibold text-brand hover:underline">Limpar filtros</Link>}</div></form></section>

    {!data.products.length ? <div className="grid place-items-center rounded-xl2 border border-dashed border-line bg-paper py-16 text-center"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-mist text-xl">□</span><p className="mt-3 font-semibold">Nenhum produto encontrado</p><p className="mt-1 text-sm text-ink-muted">Ajuste os filtros ou cadastre um novo item.</p></div> : <section className="overflow-hidden rounded-xl2 border border-line bg-paper shadow-card"><div className="hidden grid-cols-[56px_minmax(150px,1fr)_120px_105px_110px_125px] gap-3 border-b border-line bg-slate-50 px-4 py-3 text-[10px] font-bold uppercase tracking-[.12em] text-ink-muted 2xl:grid"><span>Imagem</span><span>Produto</span><span>Categoria</span><span>Preço</span><span>Estoque</span><span className="text-right">Ações</span></div><ul className="divide-y divide-line">{data.products.map((product) => {
      const stock = product.variants.length ? product.variants.reduce((sum, variant) => sum + variant.stock, 0) : product.stock;
      const discount = product.compareCents && product.compareCents > product.priceCents ? Math.round((1 - product.priceCents / product.compareCents) * 100) : 0;
      return <li key={product.id} className="grid grid-cols-[56px_minmax(0,1fr)] gap-3 px-4 py-4 transition hover:bg-brand-soft/15 sm:grid-cols-[64px_minmax(0,1fr)] 2xl:grid-cols-[56px_minmax(150px,1fr)_120px_105px_110px_125px] 2xl:items-center"><div className="relative h-14 w-14 overflow-hidden rounded-xl border border-line bg-mist"><img src={product.imageUrl} alt="" className="h-full w-full object-cover" /></div><div className="min-w-0"><div className="flex items-center gap-2"><p className="truncate text-sm font-bold">{product.name}</p>{product.featured && <span title="Destaque" className="shrink-0 text-amber-500">★</span>}</div><p className="mt-1 truncate text-xs text-ink-muted">{product.brand || "Sem marca"} · {product.variants.length ? `${product.variants.length} variação(ões)` : "Produto simples"}</p><div className="mt-2 flex flex-wrap items-center gap-1.5 2xl:hidden"><Status active={product.active} /><Stock stock={stock} /><span className="text-[11px] text-ink-muted">{formatBRL(product.priceCents)} · {product._count.reviews} avaliações · {product._count.questions} dúvidas</span></div></div><div className="hidden 2xl:block"><p className="truncate text-sm text-ink-soft">{product.category.name}</p><Status active={product.active} /></div><div className="hidden 2xl:block"><p className="text-sm font-bold">{formatBRL(product.priceCents)}</p>{discount > 0 && <p className="text-[11px] font-semibold text-emerald-700">{discount}% de desconto</p>}</div><div className="hidden 2xl:block"><Stock stock={stock} /><p className="mt-1 text-[11px] text-ink-muted">{stock} unidade(s)</p></div><div className="col-span-2 flex min-w-0 flex-wrap items-center justify-end gap-2 border-t border-line/70 pt-3 2xl:col-span-1 2xl:border-0 2xl:pt-0"><Link href={`/produtos/${product.slug}`} target="_blank" className="flex-1 whitespace-nowrap rounded-lg border border-line px-3 py-2 text-center text-xs font-semibold text-ink-soft hover:bg-mist sm:flex-none" title="Ver na loja">Ver na loja ↗</Link><Link href={`/painel/produtos/${product.id}`} className="flex-1 whitespace-nowrap rounded-lg bg-brand px-4 py-2 text-center text-xs font-bold text-white shadow-card hover:bg-brand-dark sm:flex-none">Editar produto</Link></div></li>;
    })}</ul></section>}

    <nav className="flex flex-col gap-3 rounded-xl2 border border-line bg-paper px-4 py-3 shadow-card sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-ink-muted">Mostrando <strong className="text-ink">{from}–{to}</strong> de <strong className="text-ink">{data.total}</strong></p><div className="flex items-center gap-2"><Page href={url(filters,{page:1})} disabled={page<=1}>«</Page><Page href={url(filters,{page:Math.max(1,page-1)})} disabled={page<=1}>‹</Page><span className="min-w-28 text-center text-sm font-semibold">Página {page} de {data.pageCount}</span><Page href={url(filters,{page:Math.min(data.pageCount,page+1)})} disabled={page>=data.pageCount}>›</Page><Page href={url(filters,{page:data.pageCount})} disabled={page>=data.pageCount}>»</Page></div></nav>
  </div>;
}

function Metric({ label, value, color, note }: { label: string; value: number; color: "emerald"|"amber"|"brand"|"slate"; note: string }) { const colors = { emerald: "bg-emerald-50 text-emerald-700 border-emerald-200", amber: "bg-amber-50 text-amber-700 border-amber-200", brand: "bg-brand-soft text-brand border-brand/20", slate: "bg-slate-50 text-slate-700 border-slate-200" }; return <div className={`rounded-xl2 border p-4 ${colors[color]}`}><p className="text-xs font-bold uppercase tracking-wide opacity-70">{label}</p><p className="mt-2 font-display text-3xl font-black">{value}</p><p className="mt-1 text-xs opacity-70">{note}</p></div>; }
function Status({ active }: { active: boolean }) { return <span className={`mt-1 inline-flex rounded-full px-2 py-0.5 text-[10px] font-bold ${active ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{active ? "Ativo" : "Inativo"}</span>; }
function Stock({ stock }: { stock: number }) { return <span className={`inline-flex rounded-full px-2 py-1 text-[10px] font-bold ${stock === 0 ? "bg-red-100 text-red-700" : stock <= 5 ? "bg-amber-100 text-amber-800" : "bg-emerald-100 text-emerald-700"}`}>{stock === 0 ? "Sem estoque" : stock <= 5 ? "Estoque baixo" : "Disponível"}</span>; }
function Page({ href, disabled, children }: { href: string; disabled: boolean; children: React.ReactNode }) { return <Link href={href} className={`grid h-9 w-9 place-items-center rounded-lg border border-line ${disabled ? "pointer-events-none opacity-35" : "hover:border-brand hover:text-brand"}`}>{children}</Link>; }
