import type { Metadata } from "next";
import Link from "next/link";
import { InfoPage } from "@/components/InfoPage";
export const metadata: Metadata = { title: "Política de Privacidade" };
export default function Page() { return <><InfoPage eyebrow="Legal · atualizada em 18/08/2026" title="Política de Privacidade" description="Este aviso explica quais dados a Voltaria utiliza, para quê e quais escolhas estão disponíveis a você." action={{ href: "/conta/privacidade", label: "Gerenciar meus dados", secondary: "Disponível para clientes autenticados." }} sections={[
  { title: "Dados que utilizamos", text: "Podemos tratar dados fornecidos por você e informações geradas durante o uso da loja.", items: ["Nome, e-mail e credenciais protegidas da conta", "Endereços e dados necessários à entrega", "Itens, valores e histórico dos pedidos", "Mensagens, perguntas e avaliações", "Registros técnicos necessários à segurança e funcionamento"] },
  { title: "Finalidades", text: "Os dados são usados para criar e proteger sua conta, processar pedidos, entregar produtos, prestar atendimento, cumprir obrigações e prevenir fraude. Quando uma atividade opcional depender de consentimento, você poderá rever sua escolha." },
  { title: "Pagamentos e parceiros", text: "O Mercado Pago processa a transação; a Voltaria armazena identificadores e status necessários para conciliar o pedido, não os dados completos do cartão. Serviços de hospedagem, banco de dados e entrega podem tratar apenas as informações necessárias às suas funções." },
  { title: "Prazo e segurança", text: "Mantemos dados pelo período necessário às finalidades informadas e às obrigações legais, regulatórias ou de defesa de direitos. Aplicamos controles de acesso e medidas técnicas, embora nenhum sistema conectado seja totalmente isento de risco." },
  { title: "Seus direitos", text: "Conforme aplicável, você pode pedir confirmação e acesso, correção, informação sobre compartilhamento, portabilidade, oposição, revogação do consentimento e eliminação de dados tratados com consentimento, respeitadas as hipóteses legais de conservação." },
  { title: "Como exercer", text: "Use Privacidade (LGPD) em Minha conta para exportar dados ou solicitar a exclusão. Para assuntos ligados a uma compra, utilize o atendimento dentro do pedido. Podemos confirmar sua identidade antes de atender uma solicitação." }
]} /><div className="container-x max-w-6xl -mt-4 pb-4 text-sm text-ink-muted">Veja também as <Link href="/legal/cookies" className="font-semibold text-brand hover:underline">preferências de cookies</Link> e a página de <Link href="/contato" className="font-semibold text-brand hover:underline">contato</Link>.</div></>; }
